### ISSUE TITLE
KeyError: 'lyric'

### ISSUE THREAD

**Issue by liuyunfz** [greats3an/pyncm#3]
在描述此问题前我先说一个我已解决的问题：当我尝试调用方法时提示我未找到Crypto模块，而我确认pip list后发现已安装此模块，于是我尝试重新安装pip install Crypto，不出所料提示包已存在。
解决方法：最后我通过手动查询发现package里的crypto文件夹为小写，于是我手动修改文件夹名后完成了调试，问题解决。

目前新问题的状况是ncm_func中的命令我已测试成功，但当我打算使用
```python
from ncm.ncm_func import NCMFunctions
NCM = NCMFunctions()
print(NCM.DownloadAllSongsInPlaylistAndMerge(322305604))
```
调试时却出现了以下错误
```bash
Traceback (most recent call last):
  File "d:/github/pyncm/cs.py", line 5, in <module>
    print(NCM.DownloadAllSongsInPlaylistAndMerge(322305604))
  File "d:\github\pyncm\ncm\ncm_func.py", line 408, in DownloadAllSongsInPlaylistAndMerge
    self.MutilWrapper(self.QueueDownloadAllSongsInPlaylist)(id, quality, folder,merge_only)
  File "d:\github\pyncm\ncm\ncm_func.py", line 392, in wrapper
    queue_func(id, quality, folder)
  File "d:\github\pyncm\ncm\ncm_func.py", line 160, in QueueDownloadAllSongsInPlaylist
    self.DownloadAndFormatLyrics(track_id, folder=track_root)
  File "d:\github\pyncm\ncm\ncm_func.py", line 346, in DownloadAndFormatLyrics
    self.FormatLyrics(folder)
  File "d:\github\pyncm\ncm\ncm_func.py", line 212, in FormatLyrics
    lyrics = self.LoadLyrics(folder)
  File "d:\github\pyncm\ncm\ncm_func.py", line 187, in LoadLyrics
    for lrc in lyrics.keys() if lrc in ['lrc', 'tlyric']]
  File "d:\github\pyncm\ncm\ncm_func.py", line 187, in <listcomp>
    for lrc in lyrics.keys() if lrc in ['lrc', 'tlyric']]
KeyError: 'lyric'
```

**Comment by greats3an** [comment]
这属于极端个例的情况了，原因在[这首歌](https://music.163.com/#/song?id=25713024)虽然不应有翻译后歌词`tlyrics`，但是仍然出现了该 key ,而 key 并不带内容，自然会有 `KeyError`

已在 [该commit](https://github.com/greats3an/pyncm/commit/491753128ed12eca78e722d8974976fba0977917) 中做了额外检查,dirty fix,但是能解决这个问题了

附：之前没有作说明，但是 `NCMFunctions` 和 `NeteaseCloudMusic` 两个类都是有调试输出的，详见[这里](https://github.com/greats3an/pyncm#%E6%8F%90%E4%BA%A4-issue)
